### ISSUE TITLE
Algorithms can be a bit more algorithmic

### ISSUE THREAD

**Issue by yoavweiss** [w3c/IFT#106]
General comment, but when reading through the algorithms (e.g. for how a PatchResponse is expected to be cached), it's not always clear that an algorithm is called (e.g. "go to" is sometimes used), and which algorithm handles its return values, if any.

It'd be clearer (to me, at least) to clearly mark algorithms with the definitions, have them be called (which also enables spec amenities in finding all the callers, etc) and have the callers clearly handle the return values.

**Comment by garretrieger** [comment]
Thanks for the feedback, I'll review the relevant sections and try and make them more rigorous.

**Comment by svgeesus** [comment]
see also [5.5. `var` and Algorithms](https://tabatkins.github.io/bikeshed/#var-and-algorithms) in the Bikeshed documentation
