### ISSUE TITLE
Compression performance tradeoffs

### ISSUE THREAD

**Issue by yoavweiss** [w3c/IFT#108]
Current Woff2 fonts are compressed with brotli 11 (typically), where the patch subsets are likely to be compressed with lower levels of brotli, to ensure on-the-fly compression for fast delivery. Hence, if we're expecting most of the font to be eventually downloaded, there's some cost to take into account (on top of extra requests, etc).

aside: [This research](https://dev.to/riknelix/fast-and-efficient-recompression-using-previous-compression-artifacts-47g5) may be applicable on that front and may reduce that cost, if large parts of the fonts are being downloaded.

It'd be good to clearly outline those downsides, in order to guide both user agents and developers on when they should or shouldn't be using patched incremental transfer.

The same principle also applies to range requests, which have many more downsides..

**Comment by garretrieger** [comment]
> Current Woff2 fonts are compressed with brotli 11 (typically), where the patch subsets are likely to be compressed with lower levels of brotli, to ensure on-the-fly compression for fast delivery.

That's right, for example I believe in the demo we use brotli level 9.

> Hence, if we're expecting most of the font to be eventually downloaded

I don't think this is typically going to be true. To me using IFT makes the most sense if you have a font were you're expecting to not need all of the font (for a particular user) so for example fonts that support multiple languages but individual users are expected to only some user specific subset of those, large CJK fonts that contain a core set of frequently used characters and a really long tail of very infrequently used ones, or emoji/icon fonts.

Which gets at precisely what you mentioned that we should provide guidance in the spec on when it's appropriate to use incremental transfer and when it's better to just use a single file and/or multiple files via unicode range. I'll try writing up a new section non-normative section that gives some high level guidance and explains the trade offs being made.

**Comment by svgeesus** [comment]
We should also spit the advice into alphabetic, shaping and CJK groups, like we did in the evaluagion report, because that affects how useful static subsetting it.

**Comment by yisibl** [comment]
@svgeesus Are there any plans for WOFF3? In the future, is there a better compression algorithm to solve this problem?

**Comment by svgeesus** [comment]
> Are there any plans for WOFF3? 

There are no concrete plans for WOFF3.
