### ISSUE TITLE
Optimize for one page, many pages, or both?

### ISSUE THREAD

**Issue by svgeesus** [w3c/IFT#118]
[Originally raised by Martin Thomson](https://lists.w3.org/Archives/Public/ietf-http-wg/2022AprJun/0279.html)

> Do you really want to have a different font for every page?  Is that a good outcome when every page has its own font to download?  We are dealing with similar issues with bundling of JS.  The result seems to be that you can optimize for one page, or optimize for many pages, but not both.  This specification contains none of that sort of nuance.

**Comment by svgeesus** [comment]
Note that there is a fundamental tension between, on the one hand, the desire for **best performance** (which for users of CJ fonts, means _enough performance to use the feature at all_) and on the other hand, **security and privacy concerns** which require fonts loaded for one domain not to be used on a different domain,

See

 - https://github.com/w3c/IFT/issues/43

**Comment by garretrieger** [comment]
This was pretty directly explored in the [simulations and analysis](https://www.w3.org/TR/PFE-evaluation/#analysis) which simulated and compared various ways of loading fonts including once all up front, spread out in discrete subsets (unicode range), or using incremental transfer.

One important additional thing to note is that the incremental transfer protocol allows the server to send more than the client requested. This lets the server decide where on the spectrum of one font request per page vs one big font up front to be. For example a server could be configured on the initial font load to send all characters expected to be needed across the entire site. This would give similar number of requests to loading the full font while still providing material performance improvements vs sending the whole font.

**Comment by garretrieger** [comment]
Discussed at last meeting, will add a note to the spec talking about sending more codepoints than needed to improve performance and reduce the number of requests.

**Comment by svgeesus** [comment]
@martinthomson does that path forward sound reasonable to you?

**Comment by martinthomson** [comment]
Sounds reasonable, assuming the text is adequate.

**Comment by svgeesus** [comment]
Yes, I was just wanting confirmation of the direction, not final sign-off.
