### ISSUE TITLE
Create an explainer for the IFT Patch Subset specification.

### ISSUE THREAD

**Issue by garretrieger** [w3c/IFT#124]
Chris offered to write one at the last WG meeting.

**Comment by svgeesus** [comment]
Oh, right. And we will need one for TAG review.

**Comment by svgeesus** [comment]
Currently reading the [TAG Explainer Explainer](https://github.com/w3ctag/tag.w3.org/blob/main/explainers/index.md)

**Comment by svgeesus** [comment]
[Here is a first cut](https://github.com/w3c/IFT/blob/main/Patch-Subset-Explainer.md) comments welcome.

The explainer is supposed to be short (I tried) but they also ask for a lot of information so ...

**Comment by svgeesus** [comment]
@garretrieger @vlevantovsky this is for TAG review once we publish an updated working draft.

**Comment by garretrieger** [comment]
Thanks for putting this together, looks good to me.

**Comment by vlevantovsky** [comment]
> @garretrieger @vlevantovsky this is for TAG review once we publish an updated working draft.

Thank you Chris, looks good.
