### ISSUE TITLE
Document serializing/caching of patched font

### ISSUE THREAD

**Issue by pmeenan** [w3c/IFT#196]
Maybe in non-normative notes but it might be useful to describe the process of caching the result of patching an incremental font and what the process would be in applying new patches to that file or if the patches always need to go back to the original any time a new patch needs to be added.

Just thinking through what the loading process would look like on repeat visits of a heavily patched font as a user navigates through a site.

**Comment by svgeesus** [comment]
Indeed that will be a pretty common scenario, and we should describe it more fully.

**Comment by garretrieger** [comment]
Agreed, we should add some text. As things are currently designed all state needed for IFT to operate is fully self contained in the current version of the font file, so a user agent needs to only keep a copy of the most recent font from the result of the patch application in the cache. It won't be necessary for a UA to go back to the initially loaded font.

**Comment by svgeesus** [comment]
> a user agent needs to only keep a copy of the most recent font from the result of the patch application in the cache. It won't be necessary for a UA to go back to the initially loaded font.

Agree we should explicitly state that, rather than requiring the reader to infer it.

I guess this would go in [2.1. Offline Usage](https://www.w3.org/TR/IFT/#offline-usage)?

**Comment by pmeenan** [comment]
LGTM, thanks.
