### ISSUE TITLE
Should we require Erroring on Validation Requirements for Format 1 Patch Map?

### ISSUE THREAD

**Issue by garretrieger** [w3c/IFT#198]
I've recently introduce some validation requirements to the format 1 patch map (#190 and #197). For example indices must be less than or equal to the reported maximum and in the feature map input indices may only come from the glyph map and output indices must not collide with anything in the glyph map.

Currently the specification text requires that when interpreting a format 1 table if data is found that violates these rules the entire interpretation operation fails with an error, which will in turn cause the extension operation to fail and prevent the client from further extending the font.

Checking these validation requirements would require the entirety of the format 1 table to be parsed up front. However, one of the intentions of the design of the format 1 glyph map is that it could be used in a lazy fashion. That is when locating entries which intersect the subset definition it could be done in a way where only the relevant parts of the format 1 table need to be accessed (eg. by using cmap + format 1 glyph map to locate the set of relevant entries). Thus requiring a full up front validation prevents the lazy approach from being taken by a client implementation and in some cases could significantly increase the computation cost in processing an IFT font with a very large glyph map.

Instead of making invalid data fail with an error I suggest we specify that any data which violates the validation rules is ignored. For example if a feature mapping references indices which are not in the glyph map then that particular mapping is ignored, but any other mappings which do not violate the rule may still be used. There's precedent for this in the other parts of font processing, for example shapers like harfbuzz do not error out on invalid data they just ignore it and work with whatever valid data remains.

**Comment by skef** [comment]
> Instead of making invalid data fail with an error I suggest we specify that any data which violates the validation rules is ignored. 

How path dependent is this likely to be in practice? That is, will the same data tend to be ignored, or will what gets ignored change depending on which parameters (codepoints, etc.) are patched first? 

If the results will be somewhat path dependent it might be preferable to:

1. Add a validator to the reference suite of tools.
2. Declare the behavior of invalid encodings to be undefined. 

Or something along those lines.

**Comment by garretrieger** [comment]
> > Instead of making invalid data fail with an error I suggest we specify that any data which violates the validation rules is ignored.
> 
> How path dependent is this likely to be in practice? That is, will the same data tend to be ignored, or will what gets ignored change depending on which parameters (codepoints, etc.) are patched first?
> 
> If the results will be somewhat path dependent it might be preferable to:
> 
> 1. Add a validator to the reference suite of tools.
> 2. Declare the behavior of invalid encodings to be undefined.
> 
> Or something along those lines.

The intention would be that an implementation built to fully parse the table as specified in the interpretation algorithm would always get equivalent results to an optimized implementation built to only parse the relevant parts of the format 1 table. Additionally, what gets ignored should be consistent over time and input parameters. What is considered invalid shouldn't be dependent on the input parameters, but only on data inside the table. Also what is invalid should be able to be determined when only partially parsing the table. Getting this right will be a little tricky, but I believe it should be doable.

I took a first pass at the changes to get to this point in #199 to provide a preview for what this would actually look like in practice.

**Comment by skef** [comment]
> Additionally, what gets ignored should be consistent over time and input parameters.

I'm not entirely sanguine about the "input parameters" part. Or at least I'm not sure what specifically to say about it.

I think it means that (for example), whether I'm missing glyphs *w* and *x* vs *y* and *z* on some web page will depend in part on whether I visited any other pages earlier that used the same font. Even if we say something true about consistency, that's going to look a lot like undefined behavior to anyone without a deep understanding of how all this stuff works.

**Comment by skef** [comment]
I guess there's two issues here, depending on the reader we're imagining. One is what we should tell the client-side implementations to do, which is what you're addressing. The other is accurately characterizing the impact of this approach to someone assessing the system as a whole.

If the client rejects a font with malformed tables, it works everywhere the same way. If the client ignores malformed data (in a way that depends on what it's looking for), we'll have path-dependent differences in behavior (assuming I'm right about that). I think we should make that aspect of the overall system clear.

**Comment by garretrieger** [comment]
With the changes that I made in the draft PR there shouldn't be a possibility for differences in the ignored data that is dependent on the order of patch application. My goal is: if you can scan the entirety of the table up front, and identify valid entries you should always get the same set valid entries as a client that only looks at the parts of the table relevant to it's current extension request. Thus the set of invalid and ignored entries for a particular patchmap is fixed and unchanging over time.

> I think it means that (for example), whether I'm missing glyphs _w_ and _x_ vs _y_ and _z_ on some web page will depend in part on whether I visited any other pages earlier that used the same font.

If the format 1 table has a bad entry for glyph _w_ then no matter the order of patch application for the remaining valid entries or the subset definition being used as an input, the patch for _w_ will always be considered invalid and ignored.

Additionally, we have a "must" level requirement in the encoding section requiring consistency regardless of patching order.

**Comment by garretrieger** [comment]
To make this more concrete here is the set of validation rules that I'm proposing for format 1 in the draft PR:

1. Top Level Validation:
a. Glyph count must equal maxp numGlyphs. Fail with error if it doesn't. (unchanged)
b. max entry index must be >= max glyph map entry index. Fail with error if it doesn't. (new)

2. Glyph Map validation:
a. entry index must be <= max glyph map entry index. Skip entries that violate this. (used to be error)
b. entries that have an empty code point set are skipped (new).

3. Feature Map:
a. FeatureRecords which are duplicated or not in sorted order (tag is not greater than all preceding records) are skipped. (used to be an error).
b. mapped entry index > max glyph map entry index and less than or equal to max entry index. Skip violating entries (new).
c. first entry index <= last entry index. Skip violating entries (used to be error).
d. first entry index and last entry index <= glyph map entry index. Skip violating entries (new).
e. entries that have an empty code point set are skipped (new).

All of these rules can be evaluated independently within the context of a single entry and don't depend on patch applications. So there shouldn't be any path dependent change in validation behaviour and it should be possible to validate while only looking at data for entries which may intersect the current subset definition (which allows construction of an optimized client intersection implementation).

Note: the sorting requirement for FeatureRecords does require scanning all FeatureRecords prior to the ones of interest but that list should typically be relatively small compared to the size of rest of the data being processed.
