### ISSUE TITLE
Consistently use `code point` instead of sometimes saying `codepoint`

### ISSUE THREAD

**Issue by svgeesus** [w3c/IFT#200]
One minor point I would consult with i18n is mixing use of `code point(s)` and `codepoint(s)`. Former should be our desire per glossary, but both are used in the document, such as [`codepoints` in section 3.1](https://www.w3.org/TR/2024/WD-IFT-20240709/#font-subset-dfn) or [`code points` in section 5.2.1.1](https://www.w3.org/TR/2024/WD-IFT-20240709/#interpreting-patch-map-format-1) (or detailed per step processing definitions). Should we point this?
(note, there is one parameter in structure named as [`codepoints`](https://www.w3.org/TR/2024/WD-IFT-20240709/#mapping-entry-codepoints), so some of these are correct as referencing that)

_Originally posted by @himorin in https://github.com/w3c/i18n-request/issues/238#issuecomment-2273974295_

**Comment by svgeesus** [comment]
There are 6 uses of `code point` and 42 uses of `codepoint`.

(parameters in structures should not be renamed, of course; this is about the prose)

**Comment by garretrieger** [comment]
I'll go ahead and update all uses to "code point(s)"
