### ISSUE TITLE
Advice for "on by default" features

### ISSUE THREAD

**Issue by garretrieger** [w3c/IFT#206]
This issue was brought up at the last WG call. Documenting it here.

Previously in the patch subset specification we had a list of "on by default" features. These features were considered to always be used by a shaper and thus always needed (unless explicitly opted out by the client). We likely want to give guidance in both the IFT client and encoder sections about possible special handling of these features:

1. Client: if the client implementation does not know for sure that a shaper does not need an on by default feature it should assume it's needed and include it in the extension process.
2. Encoder: encoders should consider placing on by default features into the initial subset and not having them be optional.
3. Appendix: we should add the list of on by default features, we can re-use the list previously compiled for patch subset.

**Comment by skef** [comment]
The way I think of it there are sort of three levels of client-side support when it comes to features:

1. The lowest level: The cilent doesn't know much about the shaper, so (maybe) it should ensure that anything in the list in the appendix is grabbed (if it's listed in an IFT/IFTX table).
2. The middle level: The shaper gives basic info to the client about features it may need to consult/use implicitly. The client makes sure it grabs those when they're in the tables.
3. The high level: The shaper does a pre-pass on the content and makes a list of features that could be consulted for that specific content.

I'm not sure any implementation will get around to level 3, but it can probably be explained in a couple sentences so it maybe worth including.
