### ISSUE TITLE
Discontinue the "Incremental Font Transfer via Range Request" specification

### ISSUE THREAD

**Issue by svgeesus** [w3c/IFT#230]
Range Request is no longer being developed but the Technical Reports page [still lists it](https://www.w3.org/TR/RangeRequest/) as actively developed. The Process document has a [mechanism to retire work](https://www.w3.org/policies/process/drafts/#tr-end) 

> Any [Recommendation-track](https://www.w3.org/policies/process/drafts/#w3c-recommendation-track) [technical report](https://www.w3.org/policies/process/drafts/#technical-report) no longer intended to advance or to be maintained, and that is not being rescinded, should be [published](https://www.w3.org/policies/process/drafts/#publishing) as a [Discontinued Draft](https://www.w3.org/policies/process/drafts/#discontinuedREC), with no [substantive change](https://www.w3.org/policies/process/drafts/#substantive-change) compared to the previous publication. This can happen if the [Working Group](https://www.w3.org/policies/process/drafts/#GroupsWG) decided to abandon work on the report

So we should resolve to republish Range Request as **Discontinued**. Once we have a WG decision, the [procedure is straightforward](https://www.w3.org/Guide/transitions/?profile=DISC) and I can do it.

**Comment by garretrieger** [comment]
Sounds good, we made a resolution in todays working group call to discontinue range request.

**Comment by svgeesus** [comment]
Publication requested 5 Dec, expected 10 Dec.

**Comment by svgeesus** [comment]
[Published today](https://www.w3.org/TR/2024/DISC-RangeRequest-20241210/)
