### ISSUE TITLE
Grouping of patches during extension

### ISSUE THREAD

**Issue by skef** [w3c/IFT#233]
Related to #232 

The extension algorithm says:

> For each of tables 'IFT ' and 'IFTX' (if present): convert the table into a list of entries by invoking Interpret Format 1 Patch Map or Interpret Format 2 Patch Map. Concatenate the returned entry lists into a single list, entry list.

And then later:

> Pick one entry from entry list with the following procedure:

> * If entry list contains one or more patch map entries which have a patch format that is Full Invalidation then, select exactly one of the Full Invalidation entries in entry list. The criteria for selecting the single entry is left up to the implementation to decide.

> * Otherwise if entry list contains one or more patch map entries which have a patch format that is Partial Invalidation then, select exactly one of the Partial Invalidation entries in entry list. The criteria for selecting the single entry is left up to the implementation to decide.

> * Otherwise select exactly one of the No Invalidation entries in entry list. The criteria for selecting the single entry is left up to the implementation to decide.

Why aren't we instructing people to make (up to 3) lists grouped by patch encoding, and then process those lists in the specified order? You'd never want to put them in a single list in practice and I don't see what the generality is buying us here.

**Comment by skef** [comment]
If the concern is about future patch formats that might share invalidation categories, I'm happy to have the lists grouped by invalidation category rather than format.

**Comment by garretrieger** [comment]
There's no particular reason for them to be merged into a single list, it should be functionally equivalent to have the text say to separate them into invalidation groups. I can update the text.

**Comment by garretrieger** [comment]
Related #239

**Comment by garretrieger** [comment]
Should be addressed by the #244, but feel free to reopen if more is needed.
