### ISSUE TITLE
Clear up "encoding" vs "format"

### ISSUE THREAD

**Issue by skef** [w3c/IFT#234]
Section 6.1 talks about formats. Some things referring to table 6.1 (e.g. the various patchEncoding fields) discuss these as "encodings". Given how overloaded the term "encoding" is in the spec it seems preferable to use "format" consistently for this. And maybe to always talk about either "patch format" or "map format" so that those are not confused (maybe even changing the "format" fields to "mapFormat" fields).

**Comment by garretrieger** [comment]
Sounds good to me. I'll make the changes.
