### ISSUE TITLE
Font Collection support

### ISSUE THREAD

**Issue by litherum** [w3c/IFT#28]
While some font collections exist merely for packaging convenience—a single font resource instead of several—some exist for a non-trivial size benefit, such as sharing a single 'glyf', 'CFF ', or 'CFF2' table with multiple fonts.

We should make sure that there are considerations for font collections with incremental transfer.

**Comment by garretrieger** [comment]
I think this is probably out of scope for incxfer given that @font-face doesn't support ttc's, but I suppose we way want to support it for non-browser based use cases.

For patch subset we could take two different approaches to support this use case:
1. Allow a single request to specify the have/needed state for each font in the collection. You get back a single patch.
2. Add a font index parameter to the request. Each patch request can generate a patch for a single font in the ttc at a time.

That said for patch subset, current subsetter implementations don't support subsetting entire ttc's at once. They can handle ttc's but only operate on and ouput a single font within the ttc. I also suspect that table sharing would become difficult and quite complicated once you have multiple different subsets cut on the individual fonts in the ttc.

So given the high complexity in supporting this case combined with the fact that the primary use case for incxfer does not support ttc's I lean towards not supporting it.

**Comment by jfkthame** [comment]
> I think this is probably out of scope for incxfer given that @font-face doesn't support ttc's, 

[The CSS Fonts spec](https://drafts.csswg.org/css-fonts/#font-face-src-parsing) explicitly mentions a `collection` format keyword, and notes that [a fragment identifier](https://drafts.csswg.org/css-fonts/#font-face-src-loading) is used to select an individual face.

(I'm not sure if any browser currently implements this, but it's certainly included in the spec.)

**Comment by svgeesus** [comment]
Related, we should make sure [the collections bug in the woff2 test suite](https://github.com/w3c/woff2-tests/issues/16) doesn't also affect the IFT collection tests

**Comment by svgeesus** [comment]
> [The CSS Fonts spec](https://drafts.csswg.org/css-fonts/#font-face-src-parsing) explicitly mentions a collection format keyword, and notes that [a fragment identifier](https://drafts.csswg.org/css-fonts/#font-face-src-loading) is used to select an individual face.

Defined in https://datatracker.ietf.org/doc/html/rfc8081
