### ISSUE TITLE
Method negotiation has potential time wastes in it

### ISSUE THREAD

**Issue by litherum** [w3c/IFT#30]
From https://w3c.github.io/IFT/Overview.html#negotiating-transfer-type:

> For the initial request for a font the client should assume that the server supports the patch subset based method and send a PatchRequest via HTTP GET

and in https://w3c.github.io/IFT/Overview.html#extend-subset

> If sent as a GET request the client will include a single query parameter, `request:` the value is a single `PatchRequest` object

In this design, the client sends the necessary information for both methods of IFT, and the server chooses which method it wants to reply with. Browsers have to be able to make this decision themselves - browsers are more aware of the current network conditions and the current contents of the page than the server. So, if the clients have preferences, I believe this table describes the behaviors:

&nbsp; | Client prefers patch-subset | Client prefers range-request
-- | -- | --
Server supports both methods | Client sends query parameter. Server picks which method to respond with, and client uses the magic number / `Accept-Ranges` to distinguish. Whatever method the server prefers is used. | Client omits query parameter. Server replies with `Accept-Ranges: bytes`. Range-request is used
Server only supports patch subset | Client sends query parameter. Server replies with the magic number. Patch subset method is used | Client omits query parameter. Server replies with `Accept-ranges: none`. **Client tries again**, with the query parameter this time. Server replies with the magic number. Patch subset method is used.
Server only supports range request | Client sends query parameter. Server replies with no magic number, and `Accept-Ranges: bytes`. Range request method is used. | Client omits query parameter. Server replies with `Accept-Ranges: bytes`. Range request method is used.
Server supports nothing | Client sends query parameter. Server replies with no magic number, `Accept-Ranges: none`, and sends the whole file. | Client omits query parameter. Server replies with `Accept-Ranges: none` and sends the whole file.

### Problem 1

If the server only supports patch-subset, and the client prefers range-request, the client has to retry, causing a synchronous round-trip to the server before any useful information can be transferred. I think the most natural way to solve this problem is to require that all patch-subset servers should also required to support range-requests. A patch-subset server is already smart, so there shouldn't be almost any additional implementation burden. This effectively deletes the second row of the table above.

### Problem 2

In the left column, 3 of the 4 boxes may involve the client sending a `PatchRequest` which doesn't end up being used. This could be a problem if the `PatchRequest` object is large.

Because of the CSS opt-in mechanism, it's probably safe to say that it will be rare for the browser to be trying to use IFT on a the server which support doesn't support either method. It's also probably safe to say that servers which support both methods will probably prefer patch-subset, because of the additional performance.

So, the biggest problem here is the situation where the browser prefers patch-subset, and the server only supports range requests. If the `PatchRequest` object is large, we would be spending time sending it to a server that doesn't have any idea what to do with it.

I don't actually have any good ideas about what to do about this. It would be rather unfortunate if CSS had to have two distinct opt-in mechanisms - I don't think that would be a good solution. Maybe these `PatchRequest` objects are small enough that this problem isn't necessary to solve?

**Comment by garretrieger** [comment]
Re: Problem 1: that sounds good. I can add some text to the spec stating that a patch subset supporting server must also support range request.

Re: Problem 2: I believe in the vast majority of cases the initial PatchRequest should be small enough that it won't have any meaningful impact on the overall timing of the request. To put some more concrete numbers on this:
- The main contributor to the size of the initial PatchRequest is the set of codepoints needed.
- If we assume on the high end we need about 1000 codepoints from a font, say for CJK.
- The codepoint set compression tests show we can pretty reliably encode that using ~3 bits per codepoint.
- So that gives roughly 400 bytes to represent the PatchRequest.
- This is likely small enough fit in a single packet with the rest of the http request.

**Comment by garretrieger** [comment]
Fixed by #113 which removes the uneeded PatchRequest message when initiating a range request session.
