### ISSUE TITLE
Privacy section is entirely missing

### ISSUE THREAD

**Issue by litherum** [w3c/IFT#31]
https://w3c.github.io/IFT/Overview.html#priv

> No Privacy issues have been raised against this document

This statement is false. The document needs to describe how clients must request additional unnecessary glyphs in order to dilute the signal of what content the user is viewing. Ideally, we would place some minimum requirements here to make sure a browser can't just request 0 unnecessary glyphs and claim conformance.

**Comment by garretrieger** [comment]
Right, I'll make a pass at adding that to the privacy section.

**Comment by svgeesus** [comment]
Okay [here we go](https://w3c.github.io/IFT/Overview.html#priv)
