### ISSUE TITLE
Range requests and preflights

### ISSUE THREAD

**Issue by jakearchibald** [w3c/IFT#34]
FYI, we're about to merge a change to the fetch spec that allows for particular formats of the `Range` header without needing a CORS preflight. Pretty useful for this spec 😄 

https://github.com/whatwg/fetch/pull/1312

**Comment by litherum** [comment]
Is there anything actionable here?

**Comment by jakearchibald** [comment]
I'm not sure. Is the restricted form of the `Range` header useful elsewhere?

**Comment by garretrieger** [comment]
Range request is being replaced so closing this.
