### ISSUE TITLE
Require that incrementally-loaded fonts not be preserved nor exposed to other origins

### ISSUE THREAD

**Issue by samuelweiler** [w3c/IFT#43]
The WG's answer to the S&P questionnaire says, in part:

> Web fonts are never installed on the underlying system; they are used without installation.

I don't see that restriction anywhere in the _spec_, and that restriction seems important to prevent the creation of an HSTS-like supercookie.  Where should that normative requirement be documented?

**Comment by svgeesus** [comment]
Thanks for raising this, sorry if it was unclear.

The requirement is documented in CSS Fonts 4:

>A Web Font **must not** be accessible in any other Document from the one which either is associated with the @font-face rule or owns the FontFaceSet. Other applications on the device **must not** be able to access Web Fonts.

> Installed Fonts **must not** be Web Fonts, and Web Fonts **must not** be Installed Fonts.

> https://drafts.csswg.org/css-fonts-4/#web-fonts

IFT doesn't change any aspect of CSS Fonts; the fonts are used from CSS exactly the same way. IFT just changes the network transfer aspect.

**Comment by samuelweiler** [comment]
Wonderful.  The privacy considerations should call that out.

**Comment by samuelweiler** [comment]
_In the IFT privacy considerations_, point at 10.2 of that doc, with language similar to what is in section 14.5.

**Comment by svgeesus** [comment]
I will make that change

**Comment by svgeesus** [comment]
Fixed with https://github.com/w3c/IFT/commit/91c9deb33e8f71c1e6a0e61cd17e1b4c28dfbdf8

**Comment by svgeesus** [comment]
@samuelweiler @pes10k please confirm that this recent edit satisfies your comment?

**Comment by pes10k** [comment]
Yep, looks good to me.  I think this is also solved by the fetch() text too.  Thanks!
