### ISSUE TITLE
Should fast hash be a normative reference?

### ISSUE THREAD

**Issue by svgeesus** [w3c/IFT#44]
Should [fast hash](https://github.com/ztanml/fast-hash) be a normative reference?

Or should it be an informative reference, with the pseudo-code in the spec the normative part?

(Either way it should be in the references)

**Comment by garretrieger** [comment]
I'm hesitant to use the github repo as a normative reference as it's possible it could change or be removed in the future. So my preference is to use the pseudo code as the normative reference with the fast hash repo as a reference. I'll add it to the references.
