### ISSUE TITLE
Reword definition of a correct subset and a correct subsetting operation.

### ISSUE THREAD

**Issue by svgeesus** [w3c/IFT#45]
In [2.1.1. Font Subset](https://w3c.github.io/IFT/Overview.html#font-subset):

> A subsetted font should be able to render any combination of the codepoints in the subset identically to the original font.

This is imprecise. 

1. A font doesn't render anything, it is used by some application (like a browser)  to render something.
2. An application which renders text using a font may have optional parts, or opt-in parts, and thus might render a subset and a full font identically, because it does not have a code path which is exercising the parts that should have been in the OpenType tables, or because that code path is not active.

However, this is a conformance requirement on the **font**, not on the application, so needs to be reworded to make that clear. I think it is also, primarily, a conformance requirement on the **server** that generated the subset.

As an example, consider a font subset which can only render the Latin letters **c** and **s**. The original font has **ct** and **st** ligatures. The client requests a patch for the letter **t**. A _conformant server_ must include all the tables necessary to produce the two ligatures, (making the patched font a _conformant subset_) independent of whether the browser, for example, implements [the CSS](https://drafts.csswg.org/css-fonts-4/#font-variant-ligatures-prop) `font-variant-ligatures: discretionary-ligatures` which would actually cause the **ct** ligature to be rendered.

**Comment by garretrieger** [comment]
I made an attempt at rewording the subset definition to include mention of optional features. See the above PR.

**Comment by garretrieger** [comment]
Will close for now, please reopen if you'd like any further changes.
