### ISSUE TITLE
Update CSS example for new syntax

### ISSUE THREAD

**Issue by svgeesus** [w3c/IFT#46]
In [4. Declaring Incremental Fonts](https://w3c.github.io/IFT/Overview.html#declaring-fonts) the CSS syntax is now outdated because of https://github.com/w3c/csswg-drafts/issues/6635 and https://github.com/w3c/csswg-drafts/issues/6791. The [current CSS syntax](https://drafts.csswg.org/css-fonts-4/#font-technology-definitions) would be

```css
@font-face {
  ...
  src: url(a_font.ttf) format(truetype) font-technology(incremental);
}

**Comment by svgeesus** [comment]
I'm going to hold off making that edit pending resolution of https://github.com/w3c/csswg-drafts/issues/6791

**Comment by litherum** [comment]
That issue is resolve. We should say `tech(incremental)`.
