### ISSUE TITLE
Including network state is a privacy harm (and maybe not needed)

### ISSUE THREAD

**Issue by pes10k** [w3c/IFT#49]
This issue is part of the PING privacy review https://github.com/w3cping/privacy-request/issues/61

The current spec text allows the client to include information about the current network speed.  This is a privacy harm and would allow the server to gain additional information that could be used for profiling, fingerprinting or other related privacy harms.

Since the client can already control the size and rate to request additional glyphs / font patches, this also seems to be of limited utility; the client can already request smaller (or fewer) or bigger (or larger) patches based on what it already knows about the network condition.

Finally, there are already proposals (not yet rec track, but being discussed) that would allow the client to inform the server about local network state, which the server could then use for whatever purpose desired (including possibly the uses imagined by this proposal).  https://github.com/tomayac/netinfo/blob/relaunch/README.md for example. If the authors think this funcitonality would be useful for IFT, I strongly encourage them to work on that proposal instead of possibly duplicating the informaiton here. Having all the "network state info" stuff in one spec makes the privacy analysis easier, prevents protections and choices in one proposal from undoing decisions made in the other, etc.

I recommend that the spec drop the network connection aspects all together.

**Comment by svgeesus** [comment]
Could you explain further how an (optional) assignment to one of [six speed buckets](https://w3c.github.io/IFT/Overview.html#connection-speeds) is a significant privacy harm?

(It may be, but it is not evident).

Given the significant impact of network speed, particularly for CJK fonts (see for example [figure 23](https://www.w3.org/TR/2020/NOTE-PFE-evaluation-20201015/#analysis-cjk-cost) which shows a median improvement of 90% on 4G, 55% on 3G but a median **worsening of 220%** on 2G, it is clear that ignoring network speed (throughput and latency) will result in significantly worse outcomes.

**Comment by pes10k** [comment]
There are a number of privacy issues that come from sharing network information as mentioned.  The fingerprinting risk is one, but sharing information about network speed may help an attacker identify if a user is at home, at work or on a cell connection (and there for what times of day the user is at work vs home vs traveling).  Sharing information about network speed might also help identify when the user is behind a VPN or anonymizing IP (for example, if the server sees different users connecting from one IP but reporting different network speeds).  I'm sure this is not an exhaustive list.

> The authors don't "think" this, but have clearly demonstrated it.

I appreciate the authors thing tailoring the size of updates / patches for IFT is useful, but im asking something different.  Why can't the logic for the patch size to request be pushed fully in the client, where the client could combine what it knows about the network, along with other information available to the client, to make decisions about the size of patch update to fetch?

**Comment by garretrieger** [comment]
That's a good point, I believe we should be able to accomplish what we need to by having the client use it's observed network conditions to inform the size of the request they make. Thus we can eliminate the connection speed field from the protocol. I'll create a PR with some proposed modifications.

**Comment by litherum** [comment]
During the last call I believe there was a resolution to remove the field.

**Comment by garretrieger** [comment]
The above PR removes the connection speed field, so I believe this is solved now.

**Comment by svgeesus** [comment]
@pes10k so, the **"privacy-needs-resolution"** tag could be removed on this closed issue?

**Comment by pes10k** [comment]
done and done!
