### ISSUE TITLE
Supporting fonts with composite glyphs via range-request

### ISSUE THREAD

**Issue by vlevantovsky** [w3c/IFT#58]
Based on the preliminary discussion conducted as part of [the WebFonts WG call](https://www.w3.org/2021/12/07-webfonts-minutes.html), it appears that servers replying to a range-request may be able to amend that range request and respond with a larger byte range. If this is the case, this functionality can be very useful _value-add_ for composite fonts, where a composite font preprocessing can be used to:
1. identify and group together a set of simple glyphs that are used as components, and 
2. map these sets to a range of composite glyphs that reference them.

When a range-request is submitted to include composite glyphs, a _smart_ server can amend the request to include simple components, thus avoiding any additional roundtrip requests and optimizing font sizes and user experience at the same time. The IFT Range-Request portion of the spec will not include any prescriptive text on what and how this can be done - this would be a true value-added functionality that would allow font server implementations to include additional steps and optimize user experience.

However, in order to enable this functionality to happen, certain portions of the range-request spec need to be edited - we would need to mention these possible optimization steps (both as the pre-processing step and server ability to amend range requests with larger byte range) instead of suggesting that composite fonts may not be suitable for range-request transfer and recommending that composite glyphs should be flattened to be used with range-request mechanism.

**Comment by litherum** [comment]
Right, it's reasonable to say that the server may want to respond with a larger byte range than the client requested, because the server knows more about the font than the client does.

I don't really know how to make a PR on top of a PR, but I'm happy to add text to this effect to the draft.

**Comment by vlevantovsky** [comment]
It occurred to me that a client would be in a similar position when the very first byte range request is made. Since the client doesn't know anything about the font yet (order of tables, table sizes, etc.), it would be entirely on the server to determine how much data a client should get to enable font use and the subsequent range requests.

I think adding this new text by directly editing the first draft is fine.
