### ISSUE TITLE
Method-specific privacy sections

### ISSUE THREAD

**Issue by litherum** [w3c/IFT#62]
Most of the privacy sections of the two methods should be shared, but there are probably some considerations which are distinct between the two methods.

**Comment by garretrieger** [comment]
My preference would be to have a single shared privacy section and then just be sure to mention if a specific privacy issue is specific to one method. For example in the checksum section we could add a bit of text that this is specific to patch subset.

**Comment by svgeesus** [comment]
Yes, both the Privacy and Security folks will be looking for a single section. Of course, considerations that are specific to a particular method  should be clearly identified.
