### ISSUE TITLE
Define how to handle errors

### ISSUE THREAD

**Issue by jyasskin** [w3c/IFT#68]
This specification needs to explain what the client does if the response to the fetch in https://w3c.github.io/IFT/Overview.html#extend-subset is unexpected in some way. For example, you could get a network error or non-200 status, you could get an unexpected content-type, content that isn't a CBOR-encoded PatchResponse, or a PatchResponse that violates some of the rules in https://w3c.github.io/IFT/Overview.html#handling-patch-request.

In most web specifications, there would be an algorithm with a series of steps that flows from needing to render a character that's outside the current font subset, through https://w3c.github.io/IFT/Overview.html#extend-subset, and into https://w3c.github.io/IFT/Overview.html#handling-patch-response, where you could handle errors and unexpected body contents in the [response](https://fetch.spec.whatwg.org/#concept-response), but even without that level of detail, the clients still need to handle errors.

**Comment by garretrieger** [comment]
Thanks, this is definitely missing. I'll add a section on error handling.
