### ISSUE TITLE
usage of terminology 'codepoints' in patch subset spec.

### ISSUE THREAD

**Issue by himorin** [w3c/IFT#73]
(during i18n discussion,) I personally felt that a word 'codepoints' are used as identifier of both "set of codepoints" (target codepoints which client requests and are transferred from server) and "set of glyph substitutions of font" (handled as subset of font), and I wonder this might be confusing for some readers.

**Comment by svgeesus** [comment]
Perhaps [Codepoint reordering](https://w3c.github.io/IFT/Overview.html#codepoint-reordering) should be named something more precise, like Index Generation. Because it takes codepoints as input, but does not generate new codepoints; instead it generates index values.

**Comment by himorin** [comment]
I would agree to the analysis, although some sections other than the section on `codepoint reordering` also need to be updated - which refer outputs from reordering. 
Also I suppose it might be better to think about `codepoint_ordering` also?

**Comment by svgeesus** [comment]
@garretrieger @litherum this one is not moving forward, let's discuss on the call today?

**Comment by svgeesus** [comment]
@himorin does the revised wording at [4.1. Font Subset](https://w3c.github.io/IFT/Overview.html#font-subset) and  [4.7. Codepoint Reordering](https://w3c.github.io/IFT/Overview.html#codepoint-reordering) resolve your comment?

As you will see at [4.3.3. PatchRequest](https://w3c.github.io/IFT/Overview.html#PatchRequest) `codepoint` and `glyph index` are now being used as distinct concepts.

**Comment by himorin** [comment]
@svgeesus Thank you for updates. I believe current terminologies resolve my confused points, and I am happy to close this.

**Comment by r12a** [comment]
micronit: Although i'm always tempted to write codepoint (one word), i think the more usual way (per Unicode Standard) is code points (two words). I'm sure it's perfectly understandable as is, though, so just mentioning this to be pedantic.
