### ISSUE TITLE
Specifying Range Request implementation details

### ISSUE THREAD

**Issue by vlevantovsky** [w3c/IFT#79]
One particular aspect of IFT Range Request specification is related to describing what font table data the initial request must obtain, and how to calculate glyph coverage / byte ranges for subsequent requests. The current version of the spec says nothing about it, and in order to enable compliant and testable implementations we need to provide some specific information on what UAs are expected to implement and support. One big question is how much of this coverage calculation machinery has to be specified in details? 

I think we'd need to provide more details on what range request client implementation is expected to do w.r.t. glyph coverage calculations, taking into account glyph substitutions, stylistic sets, alternate forms, etc. Leaving it open-ended for implementers to guess isn't really an option,

**Comment by litherum** [comment]
A few things that would be necessary to add:

1. Shaping can be run before any outline data has been transferred. The initial request would include enough to run shaping in its entirety.
2. CSS impacts that shaping
3. How to map glyphs to byte ranges

**Comment by garretrieger** [comment]
Range request is being replaced so closing this.
