### ISSUE TITLE
Server may reply (how else can it, while still doing patch-subset)?

### ISSUE THREAD

**Issue by svgeesus** [w3c/IFT#83]
> If the server receives the patch-subset query parameter and wishes to honor it, the server may reply with a valid [patch subset response](https://w3c.github.io/IFT/Overview.html#PatchResponse)

So, it can also honor it with some other reply? How?

I can't see why this isn't a MUST. Or (to take into account that it wants to honor it but can't recreate the client state, a SHOULD)

**Comment by garretrieger** [comment]
Sounds good, I'll make the change.

**Comment by svgeesus** [comment]
Per 17 May 2022 telcon, upgrade both of these to MUST
